project:
  type: website

website:
  title: "ISS608-VAA"
  navbar:
    left: 
    - text: "Hands-on Excercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
    - text: "In Class Excercise"
      menu: 
        - text: "In-Class Exercise 2"
          href: "In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

